import { readFileSync, writeFileSync } from 'node:fs';
const A = readFileSync('flow/shell-a.html', 'utf8');
const B = readFileSync('flow/shell-b.html', 'utf8');
const C = readFileSync('flow/shell-c.html', 'utf8');
const L = readFileSync('flow/logo-c.html', 'utf8');
const HF = readFileSync('flow/hero-c.html', 'utf8');
const T = [['index', 'Home'], ['how', 'How it works'], ['tools', 'Tools'], ['compare', 'Compare'], ['setup', 'Setup'], ['docs', 'Docs']];
const tabs = (p) => T.map(([f, l]) => "<a href='./" + f + ".html'" + (f === p ? " class='on'" : '') + '>' + l + '</a>').join('');
const hero = (e, h1, lede, cta) => HF.split('__EYE__').join(e).split('__H1__').join(h1).split('__LEDE__').join(lede).split('__CTA__').join(cta);
const shell = (f, page, title, desc, heroHtml, body) => { let s = A + B + C; s = s.split('__TITLE__').join(title); s = s.split('__DESC__').join(desc); s = s.split('__LOGO__').join(L); s = s.split('__TABS__').join(tabs(page)); s = s.split('__HERO__').join(heroHtml); s = s.split('__BODY__').join(body); writeFileSync('flow/' + f + '.html', s); console.log(f + '.html:' + s.length); };
const DESC = 'Free MCP server for the Aura public catalogue: 2,495 components, 187 skills, 30,688 assets, 725 design systems. No login. Built by swastiksingh-dev.';
const CH = "<a class='pill dark' href='./setup.html'>Set up in a minute</a><a class='pill ghost' href='./how.html'>See how it works</a>";
shell('index', 'index', 'aura-components-mcp — free Aura catalogue for every AI agent', DESC, hero('mcp server &middot; stdio &middot; zero dependencies', 'Every free thing on Aura,<br>one call away.', 'The whole free Aura catalogue behind 19 tools your agent already knows how to call. No account, no key, no browser tabs.', CH), readFileSync('flow/b-index.html', 'utf8'));
shell('how', 'how', 'How it works — aura-components-mcp', DESC, hero('how it works', 'Search small. Fetch full.<br>Paste clean.', 'Lists stay tiny, details load only for finalists, and the guide turns winners into paste-ready answers.', "<a class='pill dark' href='./tools.html'>Browse the tools</a><a class='pill ghost' href='./docs.html'>Beginner docs</a>"), readFileSync('flow/b-how.html', 'utf8'));
shell('tools', 'tools', 'Tools — aura-components-mcp', DESC, hero('19 tools', 'Every tool. Grouped by job.', 'Start at Find. Drill into one surface. Install only the winner. New badge = goes past reading.', ''), readFileSync('flow/b-tools.html', 'utf8'));
shell('compare', 'compare', 'Compare — aura-components-mcp vs official', DESC, hero('compare', 'Same family.<br>Different jobs.', 'Use both: catalogue here, account there. This page says which is which.', ''), readFileSync('flow/b-compare.html', 'utf8'));
shell('setup', 'setup', 'Setup — aura-components-mcp in a minute', DESC, hero('setup', 'In your agent<br>in a minute.', 'Clone, build, point any client at one file. Nothing to sign up for.', ''), readFileSync('flow/b-setup.html', 'utf8'));
shell('docs', 'docs', 'Docs — how aura-components-mcp works', DESC, hero('docs', 'How it works,<br>slowly.', 'New to MCP? Five minutes, top to bottom.', ''), readFileSync('flow/b-docs.html', 'utf8'));
console.log('PAGES_BUILT');
