import { loadConfig } from '../src/config.mjs';
import { createFetcher } from '../src/http.mjs';
import { createCatalog } from '../src/catalog.mjs';
import { createHandlers } from '../src/tools.mjs';
import { facets } from '../src/guide.mjs';
const cfg = loadConfig({});
const cat = createCatalog({ fetcher: createFetcher({ fetchImpl: fetch, timeoutMs: cfg.timeoutMs, retries: cfg.retries, userAgent: cfg.userAgent }), config: cfg, facetsFn: facets });
const h = createHandlers(cat);
const call = async (n, a) => JSON.parse((await h[n](a)).content[0].text);
const J = (o) => JSON.stringify(o).slice(0, 200);
const s = await call('aura_search_components', { query: 'pricing', limit: 1 });
const it = s.items[0];
console.log('ISS1 search facets: ' + J(it.facets));
const g = await call('aura_get_component', { id: it.id });
console.log('ISS1 detail code_len=' + g.item.code.length + ' facets: ' + J(g.item.facets));
console.log('ISS4 DS search:');
const ds = await call('aura_search_design_systems', { query: 'nexus-global-transfers-5', limit: 3 });
console.log(' n=' + ds.items.length + ' ' + ds.items.map((i) => i.slug + ' hp=' + i.facets.has_preview).join(' | '));
const gd = await call('aura_get_design_system', { slug: 'nexus-global-transfers-5' });
console.log('ISS4 DS detail has_preview=' + gd.item.facets.has_preview);
const ud = await call('aura_use_design_system', { slug: 'nexus-global-transfers-5' });
console.log('ISS5 TOKENS=' + JSON.stringify(ud.tokens).slice(0, 300));
console.log('ISS5 preview head=' + (gd.item.preview_html || '').slice(0, 180).replace(/\n/g, ' '));
const uu = await call('aura_use_design_system', { slug: 'nexus-global-transfers-5' });
console.log('ISS6 use deps=' + JSON.stringify(uu.install.deps));
console.log('ISS6 preview needs=' + JSON.stringify((uu.install.needs || uu.needs || null)));
const sk = await call('aura_search_skills', { query: 'landing page', limit: 10 });
const urls = {};
for (const x of sk.items) { const u = x.source_url || 'null'; urls[u] = urls[u] || []; urls[u].push(x.title.slice(0, 30)); }
for (const [u, t] of Object.entries(urls)) if (t.length > 1) console.log('ISS7 DUP url=' + u + ' titles=' + t.join(' / '));
const a = await call('aura_search_assets', { query: 'wine', limit: 2 });
console.log('ISS8 asset urls=' + a.items.map((i) => String(i.image_800w).slice(0, 60)).join(' | '));
console.log('ISS9 asset page=' + a.items.map((i) => i.page_url).join(' | '));
const rel = await call('aura_related', { kind: 'components', id: 732 });
console.log('ISS10 related premium=' + rel.related.map((i) => i.premium).join(','));
const fb = await call('aura_search_components', { query: 'xyznonexistentqqq', limit: 3 });
console.log('ISS15 nonsense: n=' + fb.items.length + ' fb=' + fb.fallback + ' sq=' + JSON.stringify(fb.suggested_queries));
const tr = await call('aura_trending', { limit: 2 });
console.log('ISS16 trend comp total=' + tr.components.total + ' views=' + tr.components.items.map((i) => i.views).join(','));
console.log('ISS16 window=' + tr.window);
const sc = await call('aura_scaffold_page', { goal: 'dark pricing', limit: 0 }).catch((e) => 'scaffold-err');
console.log('DONE');
